### ISSUE TITLE
App just crashes

### ISSUE THREAD

**Issue by schvabodka-man** [lirantal/dockly#21]
Hi there. When i'm opening dockly, i'm just getting this:

Trace: Error: Cannot read property 'length' of null
    at exitError (/usr/lib/node_modules/dockly/index.js:69:13)
    at process.on (/usr/lib/node_modules/dockly/index.js:17:7)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:296:26)

**Comment by lirantal** [comment]
Hi @schvabodka-man 
Thanks for chiming in.

A few questions to help diagnose the problem:
1. Can you check which version of dockly is installed?
2. Which OS are you on?
3. Do you have docker installed locally?
4. Do you actually have containers created? (running or stopped doesn't matter)

**Comment by schvabodka-man** [comment]
Hi! Sorry for long response

1.  2.1.1. Dockly installed from npm
2. Fedora 25
3. Yes
4. Yes, i've

**Comment by lirantal** [comment]
Thanks.

By default, dockly uses the socket to connect to the docker daemon which is usually at `/var/run/docker.sock` can you confirm that indeed it exists and works on your install?

**Comment by lirantal** [comment]
@schvabodka-man also, I released small fixes with with debug info when something happens.
can you upgrade to 2.1.2 and let me know how it works?

**Comment by lirantal** [comment]
@schvabodka-man any update?

**Comment by schvabodka-man** [comment]
Okay, sorry for long response. There is that socket in var/run. And i updated to 2.1.2 and it's still crashing with the same error. I see dockly ui for few seconds and then crash

**Comment by lirantal** [comment]
@schvabodka-man got around now to look at this again, I released 2.1.3 with:
1. better error log trace to pin-point the problem
2. caught a bug where it tries to access undefined properties of the object 

hopefully you can re-test again and share the output error log if you're still experiencing a crash.
thanks for the patience!

**Comment by lirantal** [comment]
@schvabodka-man any chance you can review my comment above to help you with the issue? thanks!

**Comment by schvabodka-man** [comment]
Still crash. Opens for a second and then

```
Trace: TypeError: Cannot read property 'length' of null
    at myWidget.update (/usr/lib/node_modules/dockly/widgets/containerUtilization.widget.js:77:118)
    at hook.dockerHook.on (/usr/lib/node_modules/dockly/widgets/containerUtilization.widget.js:21:19)
    at emitOne (events.js:96:13)
    at hook.emit (events.js:188:7)
    at utilsRepo.get.getContainerStats (/usr/lib/node_modules/dockly/hooks/containers.hook.js:65:18)
    at Object.callback (/usr/lib/node_modules/dockly/src/dockerUtil.js:117:12)
    at /usr/lib/node_modules/dockly/node_modules/dockerode/lib/container.js:937:12
    at Modem.buildPayload (/usr/lib/node_modules/dockly/node_modules/docker-modem/lib/modem.js:259:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/dockly/node_modules/docker-modem/lib/modem.js:218:14)
    at emitNone (events.js:91:20)
    at exitError (/usr/lib/node_modules/dockly/index.js:68:13)
    at process.on (/usr/lib/node_modules/dockly/index.js:17:7)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:296:26)
```

**Comment by lirantal** [comment]
@schvabodka-man ok, makes perfect sense.
released version 2.1.4 with the fix for that null case.

**Comment by lirantal** [comment]
@schvabodka-man 
I was able to reproduce the issue and committed a fix and bumped a new version.

I'm curious how you in your docker version it is unable to get the statistics for cpu and memory per container. Which docker version are you running?

**Comment by schvabodka-man** [comment]
Docker 1.12.6 on Fedora

**Comment by lirantal** [comment]
Mine is: `Docker version 17.06.0-ce, build 02c1d87` so that could be related.
Did you try the new dockly version to see if the issue resolved?

**Comment by lirantal** [comment]
@schvabodka-man if you're able to report back or still have issues I'll be more than happy to continue this thread. Thanks for all of your feedback!
